const lang = {
    en: {
        search: 'Search',
        gptSearchPlaceholder: 'What would you like to watch today?',
        home: 'Home',
        tvShows: 'TV Shows',
        movies: 'Movies',
        newAndPopular: 'New & Popular',
        myList: 'My List',
        browseByLang: 'Browse by Languages',
        account: 'Account',
        helpCenter: 'Help Center',
        signOutOfNetflix: 'Sign out of Netflix',
        fullNamePlaceholder: 'Full name',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Password',
        signIn: 'Sign In',
        signUp: 'Sign Up',
        rememberMe: 'Remember me',
        newToNetflix: 'New to Netflix?',
        signUpNow: 'Sign up Now',
        disclaimer:
            'This page is protected by Google reCAPTCHA to ensure you’re not a bot.',
        learnMore: 'Learn more',
        alreadyAMember: 'Already a member?',
    },
    hi: {
        search: 'खोज',
        gptSearchPlaceholder: 'आज आप क्या देखना चाहेंगे?',
        home: 'घर',
        tvShows: 'टीवी शो',
        movies: 'चलचित्र',
        newAndPopular: 'नया एवं लोकप्रिय',
        myList: 'मेरी सूची',
        browseByLang: 'भाषाओं के अनुसार ब्राउज़ करें',
        account: 'खाता',
        helpCenter: 'सहायता केंद्र',
        signOutOfNetflix: 'नेटफ्लिक्स से साइन आउट करें',
        fullNamePlaceholder: 'पूरा नाम',
        emailPlaceholder: 'ईमेल',
        passwordPlaceholder: 'पासवर्ड',
        signIn: 'साइन इन करें',
        signUp: 'साइन अप करें',
        rememberMe: 'मुझे याद रखें',
        newToNetflix: 'नेटफ्लिक्स में नया है?',
        signUpNow: 'अब साइन अप करें',
        disclaimer:
            'यह पृष्ठ आपको बॉट नहीं हैं यह सुनिश्चित करने के लिए Google reCAPTCHA द्वारा सुरक्षित है।',
        learnMore: 'अधिक जानें',
        alreadyAMember: 'पहले से सदस्य?',
    },
    es: {
        search: 'buscar',
        gptSearchPlaceholder: '¿Qué te gustaría ver hoy?',
        home: 'Hogar',
        tvShows: 'programas de televisión',
        movies: 'Cine',
        newAndPopular: 'Nuevo y popular',
        myList: 'mi lista',
        browseByLang: 'Navegar por idiomas',
        account: 'Cuenta',
        helpCenter: 'Centro de ayuda',
        signOutOfNetflix: 'Cerrar sesión en Netflix',
        fullNamePlaceholder: 'Nombre completo',
        emailPlaceholder: 'Correo electrónico',
        passwordPlaceholder: 'Contraseña',
        signIn: 'Registrarse',
        signUp: 'Regístrate',
        rememberMe: 'Recuérdame',
        newToNetflix: '¿Nuevo en Netflix?',
        signUpNow: 'Regístrate ahora',
        disclaimer:
            'Esta página está protegida por Google reCAPTCHA para garantizar que no eres un robot.',
        learnMore: 'Aprende más',
        alreadyAMember: '¿Ya eres miembro?',
    },
};

export default lang;
